---
- name: host servers
  hosts: nodes

  tasks:
    - name: Check variable
      debug:
        msg:  "{{ hello }}"
    - name: Create multiple files
      file:
        path: "{{ item }}"
        state: touch
      with_items:
        - test01.txt
        - test02.txt
        - test03.txt
        - test04.txt
#    - name: Check Python version and ansible version
#      shell: |
#        which ansible
#      register: check_ansible
#    - debug:
#        msg:
#          - "{{ check_ansible.stdout }}"
#          - "{{ check_ansible.stderr }}"
      # - name: check AWS S3
      #   aws_s3:
      #     bucket: www.achmadzulkarnain.com
      #     mode: list
      #   environment:
      #     AWS_ACCESS_KEY: AKIAQTFMMGTILJN4EBGB
      #     AWS_SECRET_KEY: 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
#    - aws_s3_bucket_info:
#      register: result
#      environment:
#        AWS_ACCESS_KEY: AKIAQTFMMGTILJN4EBGB
#        AWS_SECRET_KEY: "{{ ansible_password }}"
#
#    - name: List buckets
#      debug:
#        msg: "{{ result['buckets'] }}"
